const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const generateAssessmentPDF = (submissionData, filePath) => {
    return new Promise((resolve, reject) => {
        try {
            const doc = new PDFDocument();
            const stream = fs.createWriteStream(filePath);
            doc.pipe(stream);

            // Header
            doc.fontSize(20).fillColor('#0d9488').text('ExamFlow Corporate Assessment Result', { align: 'center' });
            doc.moveDown();
            doc.moveTo(0, doc.y).lineTo(doc.page.width, doc.y).strokeColor('#e2e8f0').stroke();
            doc.moveDown();

            // Employee Details
            doc.fontSize(12).fillColor('#1f2937').text(`Assessment: ${submissionData.examTitle}`);
            doc.text(`Employee: ${submissionData.employeeName}`);
            doc.text(`Date: ${new Date(submissionData.submittedAt).toLocaleString()}`);
            doc.moveDown();

            // Score
            doc.rect(50, doc.y, 500, 50).fill('#f0fdfa');
            doc.fontSize(16).fillColor('#0f766e').text(`Final Score: ${submissionData.score} / ${submissionData.totalMarks}`, 70, doc.y - 35, { align: 'center' });
            doc.moveDown(3);

            // Footer
            doc.fontSize(10).fillColor('#9ca3af').text('Generated by ExamFlow System', { align: 'center', bottom: 50 });

            doc.end();
            stream.on('finish', () => resolve(filePath));
            stream.on('error', (err) => reject(err));
        } catch (error) {
            reject(error);
        }
    });
};

module.exports = { generateAssessmentPDF };
